#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]
then
  deluser --system scmcauthd
  delgroup --system scmcauthd
  delgroup --system scmcshadow

  rmdir /run/scmcauthd || true
fi

#DEBHELPER#
