#!/bin/sh
set -e

addgroup --system scmcauthd
addgroup --system scmcshadow

adduser --system --home=/run/scmcauthd --ingroup scmcauthd scmcauthd
usermod scmcauthd -g scmcauthd -aG scmcshadow

chown scmcauthd:scmcauthd /run/scmcauthd
chmod 0710 /run/scmcauthd

systemctl daemon-reload || true
systemctl enable scmcauthd.service || true
systemctl start scmcauthd.service || true
