#!/bin/sh
set -e

addgroup --system scmcauthd
addgroup --system scmcshadow

adduser --system --home /run/scmcauthd --ingroup scmcauthd scmcauthd
usermod scmcauthd -g scmcauthd -aG scmcshadow

mkdir -p /run/scmcauthd || true
chmod 0710 /run/scmcauthd
chown scmcauthd:scmcauthd /run/scmcauthd

#DEBHELPER#
