#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]
then
  userdel --force scmcauthd || true
  groupdel scmcauthd || true
  groupdel scmcshadow || true

  rmdir /run/scmcauthd || true
fi

#DEBHELPER#
